DROP DATABASE IF EXISTS beerRatings;
CREATE DATABASE beerRatings;
USE beerRatings;

CREATE TABLE brewery (
    id INTEGER(2) AUTO_INCREMENT NOT NULL,
    name VARCHAR(15) NOT NULL,
    score INTEGER(1) NOT NULL,
    review VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);